/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      "colors": {
              "surface-deep": "#000000",
              "on-secondary-fixed-variant": "#666666",
              "on-surface-variant": "#cccccc",
              "primary": "#ffffff",
              "on-primary": "#000000",
              "on-tertiary-container": "#ffffff",
              "secondary-container": "#141414",
              "surface-bright": "#1f1f1f",
              "surface-raised": "#141414",
              "error": "#d4a017",
              "tertiary-container": "#141414",
              "background": "#000000",
              "primary-fixed": "#ffffff",
              "surface-container-low": "#0d0d0d",
              "inverse-primary": "#cccccc",
              "secondary-fixed-dim": "#999999",
              "inverse-on-surface": "#000000",
              "surface-container": "#141414",
              "surface-container-high": "#1f1f1f",
              "primary-container": "#141414",
              "on-primary-container": "#ffffff",
              "error-container": "#141414",
              "text-primary": "#ffffff",
              "on-error-container": "#d4a017",
              "on-primary-fixed-variant": "#cccccc",
              "tertiary-fixed-dim": "#999999",
              "on-tertiary-fixed-variant": "#666666",
              "tertiary-fixed": "#ffffff",
              "on-secondary-container": "#ffffff",
              "on-background": "#ffffff",
              "outline": "#262626",
              "inverse-surface": "#e6e6e6",
              "on-tertiary-fixed": "#000000",
              "secondary": "#c3d9f3",
              "on-secondary-fixed": "#000000",
              "surface": "#000000",
              "surface-dim": "#000000",
              "on-error": "#000000",
              "outline-variant": "#3a3a3a",
              "surface-variant": "#0d0d0d",
              "on-primary-fixed": "#000000",
              "primary-fixed-dim": "#cccccc",
              "tertiary": "#ffffff",
              "on-secondary": "#000000",
              "surface-container-lowest": "#000000",
              "secondary-fixed": "#c3d9f3",
              "surface-tint": "#ffffff",
              "on-surface": "#ffffff",
              "surface-container-highest": "#262626",
              "text-secondary": "#cccccc",
              "on-tertiary": "#000000"
      },
      "borderRadius": {
              "DEFAULT": "0px",
              "lg": "0px",
              "xl": "0px",
              "full": "9999px"
      },
      "spacing": {
              "base": "8px",
              "margin-mobile": "20px",
              "container-max": "1200px",
              "margin-desktop": "64px",
              "gutter": "24px"
      },
      "fontFamily": {
              "body-lg": ["Cormorant Garamond", "serif"],
              "body-md": ["Cormorant Garamond", "serif"],
              "display-lg": ["Saira Condensed", "sans-serif"],
              "label-md": ["JetBrains Mono", "monospace"],
              "display-lg-mobile": ["Saira Condensed", "sans-serif"],
              "headline-sm": ["Saira Condensed", "sans-serif"],
              "headline-md": ["Saira Condensed", "sans-serif"],
              "code": ["JetBrains Mono", "monospace"]
      },
      "fontSize": {
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "0.05em", "fontWeight": "400"}],
              "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.1em", "fontWeight": "400"}],
              "display-lg-mobile": ["36px", {"lineHeight": "42px", "letterSpacing": "0.05em", "fontWeight": "400"}],
              "headline-sm": ["24px", {"lineHeight": "32px", "letterSpacing": "0.05em", "fontWeight": "400"}],
              "headline-md": ["32px", {"lineHeight": "40px", "letterSpacing": "0.05em", "fontWeight": "400"}],
              "code": ["14px", {"lineHeight": "20px", "letterSpacing": "0.1em", "fontWeight": "400"}]
      }
    }
  },
  plugins: [],
}
