import type { Metadata } from "next";
import "./globals.css";
import CustomCursor from "@/components/CustomCursor";

export const metadata: Metadata = {
  title: "Portfolio Egi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en" className="dark">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400&family=Saira+Condensed:wght@400&family=JetBrains+Mono:wght@400&display=swap" rel="stylesheet" />
      </head>
      <body
        suppressHydrationWarning
        className={`font-body-md text-body-md antialiased overflow-x-hidden selection:bg-primary-container/30 selection:text-primary`}>
        <CustomCursor />
        {children}
      </body>
    </html>
    </>
  );
}
